name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # These three steps now run inside your project folder
      - name: Install Dependencies
        run: npm install
        working-directory: ./portfolio-website

      - name: Build
        run: npm run build
        working-directory: ./portfolio-website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # The path is now correctly pointing to the output folder
          path: ./portfolio-website/out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
